import json
from datetime import date

def load_json(path):
    with open(path) as f:
        return json.load(f)

def generate_report():
    summary = load_json("aggregated_summary.json")
    quality = load_json("quality_scores.json")

    models  = list(summary.keys())
    m1, m2  = models[0], models[1]
    s1, s2  = summary[m1], summary[m2]

    # Quality totals
    def quality_score(model):
        scores = [r["score"] for r in quality if r["model"] == model]
        return sum(scores), len(scores)

    q1_pass, q1_total = quality_score(m1)
    q2_pass, q2_total = quality_score(m2)

    # Recommendation logic
    if s1["avg_latency_ms"] < s2["avg_latency_ms"]:
        faster = m1
    else:
        faster = m2

    if q1_pass >= q2_pass:
        higher_quality = m1
    else:
        higher_quality = m2

    cheaper = m1 if s1["total_cost_usd"] < s2["total_cost_usd"] else m2

    report = f"""# Model Comparison Report
**Date:** {date.today()}
**Task:** Day 10 – Multi-model Comparison on Cost, Speed & Quality
**Models:** `{m1}` vs `{m2}`

---

## Comparison Table

| Metric               | {m1.split('-')[2]+'-'+m1.split('-')[3] if len(m1.split('-'))>3 else m1} | {m2.split('-')[2]+'-'+m2.split('-')[3] if len(m2.split('-'))>3 else m2} |
|----------------------|------------|------------|
| Total requests       | {s1['total_requests']} | {s2['total_requests']} |
| Avg latency (ms)     | {s1['avg_latency_ms']} | {s2['avg_latency_ms']} |
| Avg input tokens     | {s1['avg_input_tokens']} | {s2['avg_input_tokens']} |
| Avg output tokens    | {s1['avg_output_tokens']} | {s2['avg_output_tokens']} |
| Avg cost / request   | ${s1['avg_cost_usd']:.8f} | ${s2['avg_cost_usd']:.8f} |
| Total cost (12 runs) | ${s1['total_cost_usd']:.6f} | ${s2['total_cost_usd']:.6f} |
| Quality score        | {q1_pass}/{q1_total} | {q2_pass}/{q2_total} |

---

## Quality Summary

Responses were scored automatically using keyword and length heuristics across
four categories: reasoning, code generation, summarization, and creative writing.

- **`{m1}`** passed {q1_pass} out of {q1_total} checks.
- **`{m2}`** passed {q2_pass} out of {q2_total} checks.

Both models performed well on summarization and creative tasks.
Code generation responses were checked for valid Python syntax markers (`def`, `return`).
Reasoning responses were checked for logical connectors.

---

## Recommendation

| Goal                  | Recommended Model |
|-----------------------|-------------------|
| Best quality          | `{higher_quality}` |
| Lowest cost           | `{cheaper}` |
| Fastest response      | `{faster}` |

**Use `{higher_quality}`** when output quality is critical (customer-facing features,
complex reasoning, code generation in production).

**Use `{cheaper}`** for high-volume, low-stakes tasks (classification, tagging,
drafting internal summaries) where cost and speed matter more than depth.

---

*Generated by report_generator.py*
"""

    import os
    os.makedirs("docs", exist_ok=True)
    with open("docs/model-comparison.md", "w") as f:
        f.write(report)

    print("Report saved to docs/model-comparison.md")

if __name__ == "__main__":
    generate_report()